#!/bin/bash

# Part of the RainbowScripts suite
# License: GNU GENERAL PUBLIC LICENSE, Version 3
# 
# This script checks for updates to packages, inform the server and, if necessary
# perform a system upgrage
#
# Remember that, for a cron script to be executed, it cannot have the . in the
# file name, and PATH may need to be set
# To check for scripts executed by cron, run 
#  run-parts --test /etc/cron.daily
# Reference: https://askubuntu.com/a/112264


# aptitude search '~U' -F "%p"
# aptitude versions '?Upgradable'

# Show a message
output_message() {
  echo "${1}"
}

# Check what are the packages in the system to update
check_packages() {
  local tmp_file1=$(mktemp)
  aptitude update
  aptitude search '~U' -F "%p" > ${tmp_file1} 2>&1

  # If there are packages to update
  if [ -s "${tmp_file1}" ]; then
    local tmp_file2=$(mktemp)
    echo "Packages to update" > ${tmp_file2}
    cat ${tmp_file1} >> ${tmp_file2}
    # forge the message and send it
    cat ${tmp_file2} | rainbow-notifyadmin.sh
    rm -f ${tmp_file2}
    upgrade_packages
  fi

  rm -f ${tmp_file1}
}

upgrade_packages() {
  local tmp_file=$(mktemp)
  echo "Upgrading the system" > ${tmp_file}
  sudo aptitude -y full-upgrade -q=2 >> ${tmp_file} 2>&1
  cat ${tmp_file} | rainbow-notifyadmin.sh
  rm -f ${tmp_file}
}

check_packages