#!/bin/bash

# Part of the RainbowScripts suite
# License: GNU GENERAL PUBLIC LICENSE, Version 3
# 
# This script performs backup of important files on NAS
# The scrit is added to /etc/cron.d, so it's run in accordance with NAS wake-up time
#
# Remember that, for a cron script to be executed, it cannot have the . or - in
# the file name, and PATH may need to be set
# To check for scripts executed by cron, run 
#  run-parts --test /etc/cron.daily
# Reference: https://askubuntu.com/a/112264


# Start at 7:30 am every day, with a randon delay
30 07 * * * root /usr/local/bin/rainbow-backupnas.sh -d >/dev/null 2>&1
