#!/bin/bash

# Part of the RainbowScripts suite
# License: GNU GENERAL PUBLIC LICENSE, Version 3
# 
# This script check if an update of the Rainbow scripts is required
#
# Remember that, for a cron script to be executed, it cannot have the . in
# the file name, and PATH may need to be set
# To check for scripts executed by cron, run 
#  run-parts --test /etc/cron.daily
# Reference: https://askubuntu.com/a/112264

# Because the script may call other rainbow scripts, setting
# the path so they can be reacheable within the caller script.
export PATH="/usr/local/bin:$PATH"

/usr/loca/bin/rainbow-updater
