#!/bin/bash

# Part of the RainbowScripts suite
# License: GNU GENERAL PUBLIC LICENSE, Version 3
# 
# This script checks for updates to packages, and inform the server
#
# Remember that, for a cron script to be executed, it cannot have the . in the
# file name, and PATH may need to be set
# To check for scripts executed by cron, run 
#  run-parts --test /etc/cron.daily
# Reference: https://askubuntu.com/a/112264


# aptitude search '~U' -F "%p"
# aptitude versions '?Upgradable'

# Show a message
output_message() {
  echo "${1}"
}

# Check what are the packages in the system to update
check_packages() {
  tmp_file1=$(mktemp)
  aptitude update
  aptitude search '~U' -F "%p" > ${tmp_file1} 2>&1

  # If there are packages to update
  if [ -s "${tmp_file1}" ]; then
    tmp_file2=$(mktemp)
    output_message "Packages to update" > ${tmp_file2}
    cat ${tmp_file1} >> ${tmp_file2}
    # forge the message and send it
    cat ${tmp_file2} | rainbow-notifyadmin.sh
    rm -f ${tmp_file2}
  fi

  rm -f ${tmp_file1}
}

check_packages