#!/bin/bash

# This script is run by PAM when a new SSH login happens. It sends a
#  notification with some of the login info
#
# Requires
# - curl package (sudo apt install curl)
# - jq package (sudo apt install jq)
#
# Inspired by
# - https://blog.tommyku.com/blog/send-telegram-notification-on-ssh-login/
# - https://8192.one/post/ssh_login_notification_withtelegram/
# - https://gitlab.com/snippets/1871482#note_188602535
#
# Remember to add the following line to /etc/pam.d/sshd
# # Rainbow Scripts
# session optional pam_exec.so /usr/local/bin/rainbow-sshloginnotify
# Setting the session to ‘optional’ will allow the user to login in case the
#  script fails. (ex. Telegram servers are down) This prevents you from being
#  locked out. But setting the session to ‘required’ will enforce the
#  execution of the script as absolute
#
# The different PAM_XXX variables are here https://linux.die.net/man/8/pam_exec
#
#
# TODO
# - Call ipinfo only when the address is not a local one
# - Call all the command on a separate thread, so the login time is drastically reduced, especially in case
#    of network errors
#
# Part of the RainbowScripts suite

set -euo pipefail


if [ "${PAM_TYPE:-}" = "open_session" ]; then
  if ! hash curl 2>/dev/null || ! hash jq 2>/dev/null; then
    exit 0
  fi

  # Run asynchronously to avoid blocking the login
  (
    date_exec="$(date "+%d %b %Y %H:%M")" #Collect date & time.

    #Check what could be done querying ipinfo.io
    tmp_file="$(mktemp)" #Create a temporary file to keep data in. # True temporary file
    trap 'rm -f "$tmp_file"' EXIT

    curl "https://ipinfo.io/${PAM_RHOST:-}" -s -o "$tmp_file" #Get info on client IP.
    IP_INFOS="$(jq -r '.org + " - " + .city + ", " + .region + ", " + .country' "$tmp_file")" #Client IP info parsing via jq

    message="${PAM_USER:-unknown}@${PAM_RHOST:-unknown} login to ${PAM_SERVICE:-unknown} at $date_exec - Other info: $IP_INFOS"

    rainbow-notifytelegram "${message}" > /dev/null 2>&1 || true
  ) & disown
fi
